server:
  port: 8081

spring:
  application:
    name: order
  datasource:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/java?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
      username: root
      password: 12345678

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka

mybatis:
  type-aliases-package: com.scc.domain
  mapper-locations: classpath:mapper/*Mapper.xml
