server:
  port: 8084

#Redis数据库索引（默认为0）
#Redis服务器地址
#Redis服务器连接端口
#Redis服务器连接密码（默认为空）
#连接池最大连接数（使用负值表示没有限制）
#连接池最大阻塞等待时间（使用负值表示没有限制）
#连接池中的最大空闲连接
#连接池中的最小空闲连接
#连接超时时间（毫秒）
spring:
  application:
    name: rabbitMq
  rabbitMQ:
      host: 192.168.43.25
      port: 15672
      username: root
      password: 123456

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
