server:
  port: 8084

spring:
  application:
    name: client
  thymeleaf:
    prefix: classpath:/static/
    suffix: .html
  main:
    allow-bean-definition-overriding: true


eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka

