server:
  port: 8083

#Redis数据库索引（默认为0）
#Redis服务器地址
#Redis服务器连接端口
#Redis服务器连接密码（默认为空）
#连接池最大连接数（使用负值表示没有限制）
#连接池最大阻塞等待时间（使用负值表示没有限制）
#连接池中的最大空闲连接
#连接池中的最小空闲连接
#连接超时时间（毫秒）
spring:
  application:
    name: redis
  datasource:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/java?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
      username: root
      password: 12345678
  redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      password:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0
        timeout: 1000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka

mybatis:
  type-aliases-package: com.scc.domain
  mapper-locations: classpath:mapper/*Mapper.xml